apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auxiliary-service
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/shlomoh19/kantox-challenge.git
    targetRevision: main
    path: k8s/auxiliary-service
  
  destination:
    server: https://kubernetes.default.svc
    namespace: auxiliary-service
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true